Repository cta-sst-1m/cta-lstchain, pull requests merged in 2021-01, with the labels that each got.

#5 Add pull request template
  .github/pull_request_template.md
Labels: enhancement

#9 Lhfit highsignal gaussian approximation
  lstchain/io/lstcontainers.py
  lstchain/reco/r0_to_dl1.py
  lstchain/reco/reconstructor.py
Labels: enhancement, in progress

#11 Lhfit documentation and refactoring
  lstchain/reco/r0_to_dl1.py
  lstchain/reco/reconstructor.py
  lstchain/visualization/camera.py
Labels: documentation, done, enhancement

#13 Debug of issues introduced in untested PR
  environment.yml
  lstchain/reco/r0_to_dl1.py
  lstchain/reco/reconstructor.py
  lstchain/scripts/lstchain_mc_r0_to_dl1.py
Labels: bug, done

#14 Lhfit final gaussian approx
  lstchain/reco/r0_to_dl1.py
  lstchain/reco/reconstructor.py
Labels: done, enhancement
